### ISSUE TITLE
Accessing multiple google spread sheet

### ISSUE THREAD

**Issue by kaviproject** [times/angular-tabletop#4]
Hi ,

I am trying to access multiple google spread sheet through the Table provider but I am not able to read the second spread sheet through the config. Can you please let me know is there any method to access multiple spread sheet.

I am currently using below code for accessing one spread sheet at a time.

.config(function(TabletopProvider){
    TabletopProvider.setTabletopOptions({
      key:'https://docs.google.com/spreadsheets/d/1lizvDwl',
      simpleSheet: true
    });

**Comment by aendra-rininsland** [comment]
Hi @kaviproject!

The problem is that you can only configure a provider once per module. One option would be to create a separate module for the second sheet, then inject that as a dependency into the first module. 

See [this SO post](http://stackoverflow.com/questions/24659505/multiple-config-blocks-in-angular-module). The only difference is that you're configuring `TabletopProvider` instead of `$stateProvider`. :smile:

**Comment by kaviproject** [comment]
Thank you aendrew
